### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by stevecotton** [20kly/20kly#2] opened 2019-02-05 22:47 UTC
Hi, and thanks for this addictive game.

I've been looking at how to migrate Lightyears to Python3, and what needs fixing by hand after running the 2to3 tool. The code in Lightyears assumes that integer division returns integers, so for Python3 it needs some explicit `int`s added, otherwise mouseclicks often fail to map to the game objects.

These changes can be applied to the python2 code, leaving code that's still python2 but which 2to3 can successfully convert. I've pushed my changes to my stevecotton:version1.4/python2  and  stevecotton:version1.4/python3 branches. I haven't fixed the file handling yet, so save-games and preferences aren't saved, but the game is otherwise playable.

(Logged as an issue instead of a pull request, because there's no version1.4 branch in this repo).

**Comment by stevecotton** [comment] 2020-02-13 18:48
I finished the file handling for saves and preferences, but forgot to come back and say it was ready.

Note: python3 can load the saves generated by python2, but python2 can't load a python3 pickle, so all the config will be lost (and the savefiles be unreadable) if you run lightyears with python2 after running it with python3.

**Comment by jwhitham** [comment] 2021-03-27 13:35
Thank you for your work on this. You are absolutely right about the problems caused by the / operator and it ended up being quite a lot of work to do the Python 3 update! I am sorry that I did not eventually use your work as I wanted to follow a different path for the Py3 version, e.g. introducing regression tests before moving to Py3, but I really appreciate your efforts and your interest which helped to encourage me to make a newer version.

**Closed as completed by jwhitham** 2021-03-27 13:35 UTC
